export const tableSchedActivities = [
  {
    id: 1,
    activity: "One",
    semester: "20231",
    startDate: "2023-08-16",
    startTime: "1:00:00 PM",
    endDate: "2023-08-16",
    endTime: "1:00:00 PM",
  },
  {
    id: 2,
    activity: "Two",
    semester: "20231",
    startDate: "2023-08-16",
    startTime: "1:00:00 PM",
    endDate: "2023-08-16",
    endTime: "1:00:00 PM",
  },
  {
    id: 3,
    activity: "Three",
    semester: "20231",
    startDate: "2023-08-16",
    startTime: "1:00:00 PM",
    endDate: "2023-08-16",
    endTime: "1:00:00 PM",
  },
  {
    id: 4,
    activity: "Four",
    semester: "20231",
    startDate: "2023-08-16",
    startTime: "1:00:00 PM",
    endDate: "2023-08-16",
    endTime: "1:00:00 PM",
  },
  {
    id: 5,
    activity: "Five",
    semester: "20231",
    startDate: "2023-08-16",
    startTime: "1:00:00 PM",
    endDate: "2023-08-16",
    endTime: "1:00:00 PM",
  },
  {
    id: 6,
    activity: "Six",
    semester: "20231",
    startDate: "2023-08-16",
    startTime: "1:00:00 PM",
    endDate: "2023-08-16",
    endTime: "1:00:00 PM",
  },
  {
    id: 7,
    activity: "Seven",
    semester: "20231",
    startDate: "2023-08-16",
    startTime: "1:00:00 PM",
    endDate: "2023-08-16",
    endTime: "1:00:00 PM",
  },
  {
    id: 8,
    activity: "Eight",
    semester: "20231",
    startDate: "2023-08-16",
    startTime: "1:00:00 PM",
    endDate: "2023-08-16",
    endTime: "1:00:00 PM",
  },
  {
    id: 9,
    activity: "Nine",
    semester: "20231",
    startDate: "2023-08-16",
    startTime: "1:00:00 PM",
    endDate: "2023-08-16",
    endTime: "1:00:00 PM",
  },
  {
    id: 10,
    activity: "Ten",
    semester: "20231",
    startDate: "2023-08-16",
    startTime: "1:00:00 PM",
    endDate: "2023-08-16",
    endTime: "1:00:00 PM",
  },
  {
    id: 11,
    activity: "Eleven",
    semester: "20231",
    startDate: "2023-08-16",
    startTime: "1:00:00 PM",
    endDate: "2023-08-16",
    endTime: "1:00:00 PM",
  },
  {
    id: 12,
    activity: "Twelve",
    semester: "20231",
    startDate: "2023-08-16",
    startTime: "1:00:00 PM",
    endDate: "2023-08-16",
    endTime: "1:00:00 PM",
  },

  // Add more data as needed
];

export const tableUserType = [
  {
    id: 1,
    roleId: "AGRAD01",
    roleName: "Administrator",
  },
  {
    id: 2,
    roleId: "AGRAD02",
    roleName: "Administrator",
  },
  {
    id: 3,
    roleId: "AGRAD03",
    roleName: "Administrator",
  },
  {
    id: 4,
    roleId: "AGRAD04",
    roleName: "Administrator",
  },
  {
    id: 5,
    roleId: "AGRAD05",
    roleName: "Administrator",
  },
  {
    id: 6,
    roleId: "AGRAD06",
    roleName: "Administrator",
  },
  {
    id: 7,
    roleId: "AGRAD07",
    roleName: "Administrator",
  },
  {
    id: 8,
    roleId: "AGRAD08",
    roleName: "Administrator",
  },
  {
    id: 9,
    roleId: "AGRAD09",
    roleName: "Administrator",
  },
  {
    id: 10,
    roleId: "AGRAD010",
    roleName: "Administrator",
  },
];

export const tableUserModule = [
  {
    id: 1,
    staffID: "STAFF01",
    userID: "FAGRAD01",
    userType: "Faculty - Grad",
    name: "Juan Pepito Manaloto",
    email: "jpmanaloto2023@plm.edu.ph",
    accountExpiration: "01/01/24",
  },
  {
    id: 2,
    staffID: "STAFF02",
    userID: "FAGRAD01",
    userType: "Faculty - Grad",
    name: "Juan Pepito Manaloto",
    email: "jpmanaloto2023@plm.edu.ph",
    accountExpiration: "01/01/24",
  },
  {
    id: 3,
    staffID: "STAFF03",
    userID: "FAGRAD01",
    userType: "Faculty - Grad",
    name: "Juan Pepito Manaloto",
    email: "jpmanaloto2023@plm.edu.ph",
    accountExpiration: "01/01/24",
  },
  {
    id: 4,
    staffID: "STAFF04",
    userID: "FAGRAD01",
    userType: "Faculty - Grad",
    name: "Juan Pepito Manaloto",
    email: "jpmanaloto2023@plm.edu.ph",
    accountExpiration: "01/01/24",
  },
  {
    id: 5,
    staffID: "STAFF05",
    userID: "FAGRAD01",
    userType: "Faculty - Grad",
    name: "Juan Pepito Manaloto",
    email: "jpmanaloto2023@plm.edu.ph",
    accountExpiration: "01/01/24",
  },
  {
    id: 6,
    staffID: "STAFF06",
    userID: "FAGRAD01",
    userType: "Faculty - Grad",
    name: "Juan Pepito Manaloto",
    email: "jpmanaloto2023@plm.edu.ph",
    accountExpiration: "01/01/24",
  },
  {
    id: 7,
    staffID: "STAFF07",
    userID: "FAGRAD01",
    userType: "Faculty - Grad",
    name: "Juan Pepito Manaloto",
    email: "jpmanaloto2023@plm.edu.ph",
    accountExpiration: "01/01/24",
  },
  {
    id: 8,
    staffID: "STAFF08",
    userID: "FAGRAD01",
    userType: "Faculty - Grad",
    name: "Juan Pepito Manaloto",
    email: "jpmanaloto2023@plm.edu.ph",
    accountExpiration: "01/01/24",
  },
  {
    id: 9,
    staffID: "STAFF09",
    userID: "FAGRAD01",
    userType: "Faculty - Grad",
    name: "Philip Manaba",
    email: "jpmanaloto2023@plm.edu.ph",
    accountExpiration: "01/01/24",
  },
  {
    id: 10,
    staffID: "STAFF10",
    userID: "FAGRAD01",
    userType: "Faculty - Grad",
    name: "Tamad Garanda",
    email: "jpmanaloto2023@plm.edu.ph",
    accountExpiration: "01/01/24",
  },

  // Add more data as needed
];

export const tableEncodeRoom = [
  {
    id: 1,
    roomID: "CL001",
    roomName: "Computer Lab 1",
    building: "Gusaling Villegas",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 2,
    roomID: "CL001",
    roomName: "Computer Lab 1",
    building: "Gusaling Villegas",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 3,
    roomID: "CL001",
    roomName: "Computer Lab 1",
    building: "Gusaling Villegas",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 4,
    roomID: "CL001",
    roomName: "Computer Lab 1",
    building: "Gusaling Villegas",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 5,
    roomID: "CL001",
    roomName: "Computer Lab 1",
    building: "Gusaling Villegas",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 6,
    roomID: "CL001",
    roomName: "Computer Lab 1",
    building: "Gusaling Villegas",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 7,
    roomID: "CL001",
    roomName: "Computer Lab 1",
    building: "Gusaling Villegas",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 8,
    roomID: "CL001",
    roomName: "Computer Lab 1",
    building: "Gusaling Villegas",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 9,
    roomID: "CL001",
    roomName: "Computer Lab 1",
    building: "Gusaling Villegas",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 10,
    roomID: "CL001",
    roomName: "Computer Lab 1",
    building: "Gusaling Villegas",
    createdDate: "10-24-2023 10:00:00 PM",
  },
];

export const tableEncodeRoomBuilding = [
  {
    id: 1,
    buildingID: "CL001",
    buildingName: "Computer Lab 1",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 2,
    buildingID: "CL001",
    buildingName: "Computer Lab 1",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 3,
    buildingID: "CL001",
    buildingName: "Computer Lab 1",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 4,
    buildingID: "CL001",
    buildingName: "Computer Lab 1",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 5,
    buildingID: "CL001",
    buildingName: "Computer Lab 1",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 6,
    buildingID: "CL001",
    buildingName: "Computer Lab 1",
    createdDate: "10-24-2023 10:00:00 PM",
  },
];

export const tableEncomeMeet = [
  {
    id: 1,
    meetTypeID: "MeetTyp001",
    meetTypeCode: "Field01",
    label: "FIELD",
    activeStatus: "Active",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 2,
    meetTypeID: "MeetTyp001",
    meetTypeCode: "Field01",
    label: "FIELD",
    activeStatus: "Active",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 3,
    meetTypeID: "MeetTyp001",
    meetTypeCode: "Field01",
    label: "FIELD",
    activeStatus: "Active",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 4,
    meetTypeID: "MeetTyp001",
    meetTypeCode: "Field01",
    label: "FIELD",
    activeStatus: "Active",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 5,
    meetTypeID: "MeetTyp001",
    meetTypeCode: "Field01",
    label: "FIELD",
    activeStatus: "Active",
    createdDate: "10-24-2023 10:00:00 PM",
  },
  {
    id: 6,
    meetTypeID: "MeetTyp001",
    meetTypeCode: "Field01",
    label: "FIELD",
    activeStatus: "Active",
    createdDate: "10-24-2023 10:00:00 PM",
  },

  // Add more data as needed
];

export const tableEncodeBlock = [
  {
    id: 1,
    blockID: "2023100234",
    block: "BSCS 4-1",
    collegeID: "11",
    yearStanding: "4",
    slots: "50",
    enlisted: "37",
    dateCreated: "10-24-2023 10:00:00 PM",
  },
  {
    id: 2,
    blockID: "2023100234",
    block: "BSCS 4-1",
    collegeID: "11",
    yearStanding: "4",
    slots: "50",
    enlisted: "37",
    dateCreated: "10-24-2023 10:00:00 PM",
  },
  {
    id: 3,
    blockID: "2023100234",
    block: "BSCS 4-1",
    collegeID: "11",
    yearStanding: "4",
    slots: "50",
    enlisted: "37",
    dateCreated: "10-24-2023 10:00:00 PM",
  },
  {
    id: 4,
    blockID: "2023100234",
    block: "BSCS 4-1",
    collegeID: "11",
    yearStanding: "4",
    slots: "50",
    enlisted: "37",
    dateCreated: "10-24-2023 10:00:00 PM",
  },
  {
    id: 5,
    blockID: "2023100234",
    block: "BSCS 4-1",
    collegeID: "11",
    yearStanding: "4",
    slots: "50",
    enlisted: "37",
    dateCreated: "10-24-2023 10:00:00 PM",
  },
  {
    id: 6,
    blockID: "2023100234",
    block: "BSCS 4-1",
    collegeID: "11",
    yearStanding: "4",
    slots: "50",
    enlisted: "37",
    dateCreated: "10-24-2023 10:00:00 PM",
  },

  // Add more data as needed
];

export const tableCollegeModule = [
  {
    id: 1,
    college: "College of Engineering and Technology",
    collegeID: "1",
    unit: "CET",
    term: "3",
  },
  {
    id: 2,
    college: "College of Engineering and Technology",
    collegeID: "1",
    unit: "CET",
    term: "3",
  },
  {
    id: 3,
    college: "College of Engineering and Technology",
    collegeID: "1",
    unit: "CET",
    term: "3",
  },
  {
    id: 4,
    college: "College of Engineering and Technology",
    collegeID: "1",
    unit: "CET",
    term: "3",
  },
  {
    id: 5,
    college: "College of Engineering and Technology",
    collegeID: "1",
    unit: "CET",
    term: "3",
  },
  {
    id: 6,
    college: "College of Engineering and Technology",
    collegeID: "1",
    unit: "CET",
    term: "3",
  },

  // Add more data as needed
];

export const tableProgramModule = [
  {
    id: 1,
    programTitle:
      "Bachelor of Business Management - Master in Business Administration",
    programID: "2",
    programName: "BBM-MBA",
    collegeID: "9",
    curriculumID: "BBM-MBA2016",
    type: "M",
  },
  {
    id: 2,
    programTitle:
      "Bachelor of Business Management - Master in Business Administration",
    programID: "2",
    programName: "BBM-MBA",
    collegeID: "9",
    curriculumID: "BBM-MBA2016",
    type: "M",
  },
  {
    id: 3,
    programTitle:
      "Bachelor of Business Management - Master in Business Administration",
    programID: "2",
    programName: "BBM-MBA",
    collegeID: "9",
    curriculumID: "BBM-MBA2016",
    type: "M",
  },
  {
    id: 4,
    programTitle:
      "Bachelor of Business Management - Master in Business Administration",
    programID: "2",
    programName: "BBM-MBA",
    collegeID: "9",
    curriculumID: "BBM-MBA2016",
    type: "M",
  },
  {
    id: 5,
    programTitle:
      "Bachelor of Business Management - Master in Business Administration",
    programID: "2",
    programName: "BBM-MBA",
    collegeID: "9",
    curriculumID: "BBM-MBA2016",
    type: "M",
  },
  {
    id: 6,
    programTitle:
      "Bachelor of Business Management - Master in Business Administration",
    programID: "2",
    programName: "BBM-MBA",
    collegeID: "9",
    curriculumID: "BBM-MBA2016",
    type: "M",
  },

  // Add more data as needed
];

export const tableEmailBlast = [
  {
    id: 1,
    studentNumber: "2023-12345",
    studentName: "Juanita D. Batumbakal",
    yearLevel: "1",
    program: "BSCS",
    college: "CET",
    personalEmail: "jdbatumbakal@gmail.com",
  },
  {
    id: 2,
    studentNumber: "2023-12345",
    studentName: "Juanita D. Batumbakal",
    yearLevel: "1",
    program: "BSCS",
    college: "CET",
    personalEmail: "jdbatumbakal@gmail.com",
  },
  {
    id: 3,
    studentNumber: "2023-12345",
    studentName: "Juanita D. Batumbakal",
    yearLevel: "1",
    program: "BSCS",
    college: "CET",
    personalEmail: "jdbatumbakal@gmail.com",
  },
  {
    id: 4,
    studentNumber: "2023-12345",
    studentName: "Juanita D. Batumbakal",
    yearLevel: "1",
    program: "BSCS",
    college: "CET",
    personalEmail: "jdbatumbakal@gmail.com",
  },
  {
    id: 5,
    studentNumber: "2023-12345",
    studentName: "Juanita D. Batumbakal",
    yearLevel: "1",
    program: "BSCS",
    college: "CET",
    personalEmail: "jdbatumbakal@gmail.com",
  },
  {
    id: 6,
    studentNumber: "2023-12345",
    studentName: "Juanita D. Batumbakal",
    yearLevel: "1",
    program: "BSCS",
    college: "CET",
    personalEmail: "jdbatumbakal@gmail.com",
  },

  // Add more data as needed
];

export const tableStudentReg = [
  {
    id: 1,
    studentNumber: "2023-12345",
    studentName: "Juanita D. Batumbakal",
    yearLevel: "1",
    program: "BSCS",
    college: "CET",
    sem: "20231",
    status: "Regular",
  },
  {
    id: 2,
    studentNumber: "2023-12345",
    studentName: "Juanita D. Batumbakal",
    yearLevel: "1",
    program: "BSCS",
    college: "CET",
    sem: "20231",
    status: "Regular",
  },
  {
    id: 3,
    studentNumber: "2023-12345",
    studentName: "Juanita D. Batumbakal",
    yearLevel: "1",
    program: "BSCS",
    college: "CET",
    sem: "20231",
    status: "Regular",
  },
  {
    id: 4,
    studentNumber: "2023-12345",
    studentName: "Juanita D. Batumbakal",
    yearLevel: "1",
    program: "BSCS",
    college: "CET",
    sem: "20231",
    status: "Regular",
  },
  {
    id: 5,
    studentNumber: "2023-12345",
    studentName: "Juanita D. Batumbakal",
    yearLevel: "1",
    program: "BSCS",
    college: "CET",
    sem: "20231",
    status: "Regular",
  },
  {
    id: 6,
    studentNumber: "2023-12345",
    studentName: "Juanita D. Batumbakal",
    yearLevel: "1",
    program: "BSCS",
    college: "CET",
    sem: "20231",
    status: "Regular",
  },
  {
    id: 7,
    studentNumber: "2023-12345",
    studentName: "Juanita D. Batumbakal",
    yearLevel: "1",
    program: "BSCS",
    college: "CET",
    sem: "20231",
    status: "Regular",
  },
  {
    id: 8,
    studentNumber: "2023-12345",
    studentName: "Juanita D. Batumbakal",
    yearLevel: "1",
    program: "BSCS",
    college: "CET",
    sem: "20231",
    status: "Regular",
  },

  // Add more data as needed
];
